name: Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      node:
        required: true
        type: string
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      personal-access-token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Output the input value
        run: |
          echo "The node version to use is: ${{ inputs.node }}"
